package com.example.demo.repository;

import org.springframework.data.mongodb.core.aggregation.AggregationResults;
import org.springframework.data.mongodb.repository.Aggregation;
import org.springframework.data.mongodb.repository.MongoRepository;

import com.example.demo.entity.TempLogDetails;

@org.springframework.stereotype.Repository
public interface Repository extends MongoRepository<TempLogDetails, String> {

	@Aggregation(pipeline = {
			"{$match: {\r\n"
			+ " $and: [\r\n"
			+ "  {\r\n"
			+ "   createdOn: {\r\n"
			+ "    $gte: ISODate('2022-11-01T00:00:00.000Z')\r\n"
			+ "   }\r\n"
			+ "  },\r\n"
			+ "  {\r\n"
			+ "   stateId: {\r\n"
			+ "    $nin: [\r\n"
			+ "     0\r\n"
			+ "    ]\r\n"
			+ "   }\r\n"
			+ "  }\r\n"
			+ " ]\r\n"
			+ "}}",
			"{$sort: { _id: 1}}",
			"{$project: {\r\n"
			+ " dId: 1,\r\n"
			+ " assetDId: 1,\r\n"
			+ " sId: 1,\r\n"
			+ " tmp: 1,\r\n"
			+ " statusId: 1,\r\n"
			+ " stateId: 1,\r\n"
			+ " districtId: 1,\r\n"
			+ " storeName: 1,\r\n"
			+ " storeId: 1,\r\n"
			+ " vendorName: 1,\r\n"
			+ " vendorId: 1,\r\n"
			+ " assetModelId: 1,\r\n"
			+ " assetTypeName: 1,\r\n"
			+ " assetTypeId: 1,\r\n"
			+ " temperatureLogTime: 1,\r\n"
			+ " createdOn: 1,\r\n"
			+ " time: {\r\n"
			+ "  $toLong: '$createdOn'\r\n"
			+ " },\r\n"
			+ " stage: {\r\n"
			+ "  $switch: {\r\n"
			+ "   branches: [\r\n"
			+ "    {\r\n"
			+ "     'case': {\r\n"
			+ "      $and: [\r\n"
			+ "       {\r\n"
			+ "        $in: [\r\n"
			+ "         '$sId',\r\n"
			+ "         [\r\n"
			+ "          'A',\r\n"
			+ "          'B',\r\n"
			+ "          'C',\r\n"
			+ "          'E'\r\n"
			+ "         ]\r\n"
			+ "        ]\r\n"
			+ "       },\r\n"
			+ "       {\r\n"
			+ "        $gte: [\r\n"
			+ "         '$tmp',\r\n"
			+ "         10\r\n"
			+ "        ]\r\n"
			+ "       }\r\n"
			+ "      ]\r\n"
			+ "     },\r\n"
			+ "     then: 'high'\r\n"
			+ "    },\r\n"
			+ "    {\r\n"
			+ "     'case': {\r\n"
			+ "      $and: [\r\n"
			+ "       {\r\n"
			+ "        $in: [\r\n"
			+ "         '$sId',\r\n"
			+ "         [\r\n"
			+ "          'D'\r\n"
			+ "         ]\r\n"
			+ "        ]\r\n"
			+ "       },\r\n"
			+ "       {\r\n"
			+ "        $gte: [\r\n"
			+ "         '$tmp',\r\n"
			+ "         50\r\n"
			+ "        ]\r\n"
			+ "       }\r\n"
			+ "      ]\r\n"
			+ "     },\r\n"
			+ "     then: 'high'\r\n"
			+ "    },\r\n"
			+ "    {\r\n"
			+ "     'case': {\r\n"
			+ "      $and: [\r\n"
			+ "       {\r\n"
			+ "        $in: [\r\n"
			+ "         '$sId',\r\n"
			+ "         [\r\n"
			+ "          'A',\r\n"
			+ "          'B',\r\n"
			+ "          'C',\r\n"
			+ "          'E'\r\n"
			+ "         ]\r\n"
			+ "        ]\r\n"
			+ "       },\r\n"
			+ "       {\r\n"
			+ "        $lte: [\r\n"
			+ "         '$tmp',\r\n"
			+ "         2\r\n"
			+ "        ]\r\n"
			+ "       }\r\n"
			+ "      ]\r\n"
			+ "     },\r\n"
			+ "     then: 'low'\r\n"
			+ "    },\r\n"
			+ "    {\r\n"
			+ "     'case': {\r\n"
			+ "      $and: [\r\n"
			+ "       {\r\n"
			+ "        $in: [\r\n"
			+ "         '$sId',\r\n"
			+ "         [\r\n"
			+ "          'D'\r\n"
			+ "         ]\r\n"
			+ "        ]\r\n"
			+ "       },\r\n"
			+ "       {\r\n"
			+ "        $lte: [\r\n"
			+ "         '$tmp',\r\n"
			+ "         -30\r\n"
			+ "        ]\r\n"
			+ "       }\r\n"
			+ "      ]\r\n"
			+ "     },\r\n"
			+ "     then: 'low'\r\n"
			+ "    },\r\n"
			+ "    {\r\n"
			+ "     'case': true,\r\n"
			+ "     then: 'normal'\r\n"
			+ "    }\r\n"
			+ "   ]\r\n"
			+ "  }\r\n"
			+ " }\r\n"
			+ "}}",
			"{$group: {\r\n"
			+ " _id: {\r\n"
			+ "  dId: '$dId',\r\n"
			+ "  sId: '$sId'\r\n"
			+ " },\r\n"
			+ " data: {\r\n"
			+ "  $push: {\r\n"
			+ "   time: '$time',\r\n"
			+ "   stage: '$stage',\r\n"
			+ "   tmp: '$tmp'\r\n"
			+ "  }\r\n"
			+ " },\r\n"
			+ " details: {\r\n"
			+ "  $addToSet: {\r\n"
			+ "   assetDId: '$assetDId',\r\n"
			+ "   statusId: '$statusId',\r\n"
			+ "   stateId: '$stateId',\r\n"
			+ "   districtId: '$districtId',\r\n"
			+ "   storeName: '$storeName',\r\n"
			+ "   storeId: '$storeId',\r\n"
			+ "   vendorName: '$vendorName',\r\n"
			+ "   vendorId: '$vendorId',\r\n"
			+ "   assetModelId: '$assetModelId',\r\n"
			+ "   assetTypeName: '$assetTypeName',\r\n"
			+ "   assetTypeId: '$assetTypeId'\r\n"
			+ "  }\r\n"
			+ " }\r\n"
			+ "}}",
			"{$addFields: {\r\n"
			+ " durations: {\r\n"
			+ "  $reduce: {\r\n"
			+ "   input: '$data',\r\n"
			+ "   initialValue: {\r\n"
			+ "    pvsStage: null,\r\n"
			+ "    highStartTime: null,\r\n"
			+ "    totalHighDuration: 0,\r\n"
			+ "    lastHighTemp: null,\r\n"
			+ "    lastHighTime: null\r\n"
			+ "   },\r\n"
			+ "   'in': {\r\n"
			+ "    pvsStage: '$$this.stage',\r\n"
			+ "    highStartTime: {\r\n"
			+ "     $cond: [\r\n"
			+ "      {\r\n"
			+ "       $and: [\r\n"
			+ "        {\r\n"
			+ "         $eq: [\r\n"
			+ "          '$$this.stage',\r\n"
			+ "          'high'\r\n"
			+ "         ]\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "         $ne: [\r\n"
			+ "          '$$value.pvsStage',\r\n"
			+ "          'high'\r\n"
			+ "         ]\r\n"
			+ "        }\r\n"
			+ "       ]\r\n"
			+ "      },\r\n"
			+ "      '$$this.time',\r\n"
			+ "      '$$value.highStartTime'\r\n"
			+ "     ]\r\n"
			+ "    },\r\n"
			+ "    totalHighDuration: {\r\n"
			+ "     $cond: [\r\n"
			+ "      {\r\n"
			+ "       $or: [\r\n"
			+ "        {\r\n"
			+ "         $and: [\r\n"
			+ "          {\r\n"
			+ "           $ne: [\r\n"
			+ "            '$$this.stage',\r\n"
			+ "            'high'\r\n"
			+ "           ]\r\n"
			+ "          },\r\n"
			+ "          {\r\n"
			+ "           $eq: [\r\n"
			+ "            '$$value.pvsStage',\r\n"
			+ "            'high'\r\n"
			+ "           ]\r\n"
			+ "          }\r\n"
			+ "         ]\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "         $and: [\r\n"
			+ "          {\r\n"
			+ "           $eq: [\r\n"
			+ "            '$$this.stage',\r\n"
			+ "            'high'\r\n"
			+ "           ]\r\n"
			+ "          },\r\n"
			+ "          {\r\n"
			+ "           $eq: [\r\n"
			+ "            '$$value.pvsStage',\r\n"
			+ "            'high'\r\n"
			+ "           ]\r\n"
			+ "          },\r\n"
			+ "          {\r\n"
			+ "           $eq: [\r\n"
			+ "            {\r\n"
			+ "             $indexOfArray: [\r\n"
			+ "              '$data',\r\n"
			+ "              '$$this'\r\n"
			+ "             ]\r\n"
			+ "            },\r\n"
			+ "            {\r\n"
			+ "             $subtract: [\r\n"
			+ "              {\r\n"
			+ "               $size: '$data'\r\n"
			+ "              },\r\n"
			+ "              1\r\n"
			+ "             ]\r\n"
			+ "            }\r\n"
			+ "           ]\r\n"
			+ "          }\r\n"
			+ "         ]\r\n"
			+ "        }\r\n"
			+ "       ]\r\n"
			+ "      },\r\n"
			+ "      {\r\n"
			+ "       $add: [\r\n"
			+ "        '$$value.totalHighDuration',\r\n"
			+ "        {\r\n"
			+ "         $subtract: [\r\n"
			+ "          '$$this.time',\r\n"
			+ "          '$$value.highStartTime'\r\n"
			+ "         ]\r\n"
			+ "        }\r\n"
			+ "       ]\r\n"
			+ "      },\r\n"
			+ "      '$$value.totalHighDuration'\r\n"
			+ "     ]\r\n"
			+ "    },\r\n"
			+ "    lastHighTemp: {\r\n"
			+ "     $cond: [\r\n"
			+ "      {\r\n"
			+ "       $and: [\r\n"
			+ "        {\r\n"
			+ "         $eq: [\r\n"
			+ "          '$$this.stage',\r\n"
			+ "          'high'\r\n"
			+ "         ]\r\n"
			+ "        }\r\n"
			+ "       ]\r\n"
			+ "      },\r\n"
			+ "      '$$this.tmp',\r\n"
			+ "      '$$value.lastHighTemp'\r\n"
			+ "     ]\r\n"
			+ "    },\r\n"
			+ "    lastHighTime: {\r\n"
			+ "     $cond: [\r\n"
			+ "      {\r\n"
			+ "       $and: [\r\n"
			+ "        {\r\n"
			+ "         $eq: [\r\n"
			+ "          '$$this.stage',\r\n"
			+ "          'high'\r\n"
			+ "         ]\r\n"
			+ "        }\r\n"
			+ "       ]\r\n"
			+ "      },\r\n"
			+ "      '$$this.time',\r\n"
			+ "      '$$value.lastHighTime'\r\n"
			+ "     ]\r\n"
			+ "    }\r\n"
			+ "   }\r\n"
			+ "  }\r\n"
			+ " }\r\n"
			+ "}}",
"{$match: {\r\n"
+ " 'durations.totalHighDuration': {\r\n"
+ "  $gte: 86400000\r\n"
+ " }\r\n"
+ "}}",
"{$project: {\r\n"
+ " _id: 0,\r\n"
+ " dId: '$_id.dId',\r\n"
+ " sId: '$_id.sId',\r\n"
+ " assetDId: {\r\n"
+ "  $arrayElemAt: [\r\n"
+ "   '$details.assetDId',\r\n"
+ "   0\r\n"
+ "  ]\r\n"
+ " },\r\n"
+ " statusId: {\r\n"
+ "  $arrayElemAt: [\r\n"
+ "   '$details.statusId',\r\n"
+ "   0\r\n"
+ "  ]\r\n"
+ " },\r\n"
+ " stateId: {\r\n"
+ "  $arrayElemAt: [\r\n"
+ "   '$details.stateId',\r\n"
+ "   0\r\n"
+ "  ]\r\n"
+ " },\r\n"
+ " districtId: {\r\n"
+ "  $arrayElemAt: [\r\n"
+ "   '$details.districtId',\r\n"
+ "   0\r\n"
+ "  ]\r\n"
+ " },\r\n"
+ " storeName: {\r\n"
+ "  $arrayElemAt: [\r\n"
+ "   '$details.storeName',\r\n"
+ "   0\r\n"
+ "  ]\r\n"
+ " },\r\n"
+ " storeId: {\r\n"
+ "  $arrayElemAt: [\r\n"
+ "   '$details.storeId',\r\n"
+ "   0\r\n"
+ "  ]\r\n"
+ " },\r\n"
+ " vendorName: {\r\n"
+ "  $arrayElemAt: [\r\n"
+ "   '$details.vendorName',\r\n"
+ "   0\r\n"
+ "  ]\r\n"
+ " },\r\n"
+ " vendorId: {\r\n"
+ "  $arrayElemAt: [\r\n"
+ "   '$details.vendorId',\r\n"
+ "   0\r\n"
+ "  ]\r\n"
+ " },\r\n"
+ " assetModelId: {\r\n"
+ "  $arrayElemAt: [\r\n"
+ "   '$details.assetModelId',\r\n"
+ "   0\r\n"
+ "  ]\r\n"
+ " },\r\n"
+ " assetTypeName: {\r\n"
+ "  $arrayElemAt: [\r\n"
+ "   '$details.assetTypeName',\r\n"
+ "   0\r\n"
+ "  ]\r\n"
+ " },\r\n"
+ " assetTypeId: {\r\n"
+ "  $arrayElemAt: [\r\n"
+ "   '$details.assetTypeId',\r\n"
+ "   0\r\n"
+ "  ]\r\n"
+ " },\r\n"
+ " totalHighDuration: '$durations.totalHighDuration',\r\n"
+ " lastHighTemp: '$durations.lastHighTemp',\r\n"
+ " lastHighTime: '$durations.lastHighTime'\r\n"
+ "}}"
			
			})
			AggregationResults<TempLogDetails> getHighTimeDuration();
		}
